---
server:
  contextPath: /tikbiz
---
spring:
  thymeleaf:
    mode: LEGACYHTML5
---
spring:
  profiles: local, default
datasource:
  tikbizapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  tikbizapp:
    url: jdbc:mysql://localhost:3306/tikbizapp
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
logging:
    level:
       root: INFO
    org.springframework.web: INFO
---
tikbiz:
    shift:
       start:
          message: Your Shift is about to start in 4 hours from now, Thanks.

