---
server:
  contextPath: /tikbiz
---
spring:
  thymeleaf:
    mode: LEGACYHTML5
---
spring:
  profiles: local, default
datasource:
  tikbizapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  tikbizapp:
    url: jdbc:mysql://localhost:3306/tikbizapp
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
logging:
    level:
       root: INFO
    org.springframework.web: INFO
---
tikbiz:
    message:
       shiftstart: Your Shift is about to start in 4 hours from now, Thanks.
       escalation: Ticket #{0} raised at Priority level {1} is not yet looked into, please provide necessary support.
       userticket: Ticket #{0} of priority {1} has been created.
       supportticket: 
    sms:
       endpoint: https://www.smsgatewayhub.com/api/mt/SendSMS?APIKey=8Dza5VhlaE2KvN7n1l59NA&senderid=TESTIN&channel=2&DCS=0&flashsms=0&number={0}&text={1}&route=11

